# Generated by Django 4.2.8 on 2023-12-28 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proj_type",
                    models.CharField(
                        choices=[
                            ("1", "Эксплуатация"),
                            ("2", "Техническое обслуживание"),
                            ("3", "СМР"),
                            ("4", "Производство"),
                        ],
                        default="EXP",
                        max_length=3,
                        verbose_name="Статус объекта",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "reg_num",
                    models.CharField(
                        max_length=255, verbose_name="Регистрационный № ОПО"
                    ),
                ),
                (
                    "contract",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Договор"
                    ),
                ),
                ("date_creation", models.DateField(verbose_name="Дата договора")),
                (
                    "date_notification",
                    models.DateField(verbose_name="Дата(для оповещения)"),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Тип объекта"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Контактный человек"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Контактный телефон"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Контактный e-mail"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "В работе"),
                            ("2", "ПНР"),
                            ("3", "Сезон откл."),
                            ("4", "СМР"),
                            ("5", "Аварийное откл."),
                        ],
                        default="1",
                        max_length=4,
                        verbose_name="Статус объекта",
                    ),
                ),
                (
                    "seasoning",
                    models.CharField(
                        choices=[("1", "Сезонная"), ("2", "Круглогодичная")],
                        default="1",
                        max_length=4,
                        verbose_name="Сезонность",
                    ),
                ),
                (
                    "cost",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Цена обслуживания"
                    ),
                ),
                (
                    "project_to_user",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="project_to_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объекты",
                "verbose_name_plural": "Объекты",
            },
        ),
    ]
