# Generated by Django 4.2.8 on 2023-12-28 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="project_to_user",
            field=models.ManyToManyField(
                blank=True,
                related_name="project_to_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователи",
            ),
        ),
    ]
