# Generated by Django 4.2.8 on 2024-01-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0002_alter_projects_project_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Цена обслуживания"
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="date_creation",
            field=models.DateField(auto_now=True, verbose_name="Дата договора"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="date_notification",
            field=models.DateField(auto_now=True, verbose_name="Дата(для оповещения)"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="proj_type",
            field=models.CharField(
                choices=[
                    ("1", "Эксплуатация"),
                    ("2", "Техническое обслуживание"),
                    ("3", "СМР"),
                    ("4", "Производство"),
                ],
                default="1",
                max_length=3,
                verbose_name="Статус объекта",
            ),
        ),
    ]
