# Generated by Django 4.2.8 on 2024-01-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_app",
            "0003_alter_projects_cost_alter_projects_date_creation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="date_creation",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="Дата договора"
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="date_notification",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="Дата(для оповещения)"
            ),
        ),
    ]
