# Generated by Django 4.2.8 on 2024-03-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0004_alter_projects_date_creation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="is_archived",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Архивный"
            ),
        ),
    ]
