# Generated by Django 4.2.8 on 2024-03-21 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0005_projects_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusChoiceChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "Статус"), ("2", "Цена")],
                        default="2",
                        max_length=1,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "value",
                    models.FloatField(blank=True, null=True, verbose_name="Значение"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "В работе"),
                            ("2", "ПНР"),
                            ("3", "Сезон откл."),
                            ("4", "СМР"),
                            ("5", "Аварийное откл."),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("date", models.DateField(auto_now=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_app.projects",
                    ),
                ),
            ],
        ),
    ]
