# Generated by Django 4.2.8 on 2024-03-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_app", "0006_statuschoicechange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuschoicechange",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
