# Generated by Django 4.2.8 on 2024-02-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mails",
            name="created",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="mails",
            name="date_reg",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="mails",
            name="naming",
            field=models.CharField(
                blank=True,
                max_length=1023,
                null=True,
                verbose_name="Наименование отправителя/получателя",
            ),
        ),
        migrations.AlterField(
            model_name="mails",
            name="number",
            field=models.CharField(
                blank=True, max_length=1023, null=True, verbose_name="Номер"
            ),
        ),
        migrations.AlterField(
            model_name="mails",
            name="type",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Тип"
            ),
        ),
    ]
