# Generated by Django 4.2.8 on 2024-02-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_app", "0002_alter_mails_created_alter_mails_date_reg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mails",
            name="doc",
            field=models.FileField(
                blank=True, null=True, upload_to="media/", verbose_name="Документ"
            ),
        ),
    ]
