# Generated by Django 4.2.8 on 2024-05-07 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_app", "0004_mails_completion_in_mails_completion_out_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mails",
            name="mail_to_message",
        ),
    ]
