# Generated by Django 4.2.8 on 2024-01-26 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_app", "0004_alter_projects_date_creation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=1024, null=True, verbose_name="Сообщение"
                    ),
                ),
                ("created", models.DateField(auto_now=True, null=True)),
                (
                    "doc",
                    models.FileField(blank=True, null=True, upload_to="messages_docs"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_app.projects",
                    ),
                ),
            ],
        ),
    ]
