# Generated by Django 4.2.8 on 2024-01-30 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0004_alter_tasks_name"),
        ("message_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="task_app.tasks"
            ),
        ),
    ]
