# Generated by Django 4.2.8 on 2024-02-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message_app", "0002_alter_messages_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messages",
            options={"verbose_name": "Сообщения", "verbose_name_plural": "Сообщения"},
        ),
    ]
