# Generated by Django 4.2.8 on 2024-02-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_app", "0003_alter_messages_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="doc",
            field=models.FileField(blank=True, null=True, upload_to="media"),
        ),
    ]
