# Generated by Django 4.2.8 on 2024-05-07 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mail_app", "0005_remove_mails_mail_to_message"),
        ("task_app", "0006_tasks_description_tasks_doc"),
        ("message_app", "0004_alter_messages_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="mail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mail_app.mails",
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="task_app.tasks",
            ),
        ),
    ]
