# Generated by Django 4.2.8 on 2023-12-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_app",
            "0003_alter_customuser_options_alter_customuser_managers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="attestation",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Аттестация"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_of_start",
            field=models.DateField(blank=True, null=True, verbose_name="Дата начала"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="info_about_relocate",
            field=models.TextField(
                blank=True,
                max_length=511,
                null=True,
                verbose_name="Информация о переводе",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="inn",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="ИНН"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="passport",
            field=models.TextField(
                blank=True, max_length=256, null=True, verbose_name="Паспорт"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="post",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Должность"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="qualification",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Повышение квалификации",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="retraining",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Проф. подготовка"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="snils",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="СНИЛС"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Статус"),
        ),
    ]
