# Generated by Django 4.2.8 on 2024-02-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0004_customuser_address_customuser_attestation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователи",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
