# Generated by Django 4.2.8 on 2024-03-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0005_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
