# Generated by Django 4.2.8 on 2024-03-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0006_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="isDark",
            field=models.BooleanField(default=True, verbose_name="Тема"),
        ),
    ]
