# Generated by Django 4.2.8 on 2024-03-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0007_customuser_isdark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="isDark",
            new_name="is_dark",
        ),
    ]
