# Generated by Django 4.2.8 on 2024-02-16 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_app", "0004_alter_projects_date_creation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование документа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "Без статуса"),
                            ("2", "Черновик"),
                            ("3", "На согласовании"),
                            ("4", "Действующий"),
                            ("5", "Завершённый"),
                            ("6", "Расторгнутый"),
                            ("7", "Аннулированный"),
                        ],
                        default="CU",
                        max_length=4,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("01", "Договор"),
                            ("02", "Регистрация объекта в государственном реестре"),
                            ("03", "Правоустанавливающие документы"),
                            ("04", "Проектные документы"),
                            ("05", "Экспертиза"),
                            ("06", "Страхование"),
                            (
                                "07",
                                "Разрешительные документы и акты ввода в эксплуатацию",
                            ),
                            (
                                "08",
                                "Исполнительно-техническая документация по строительству",
                            ),
                            ("09", "Эксплуатационные документы"),
                            ("10", "Обучение персонала"),
                            ("11", "Документы сезонные в эксплуатационный период"),
                            ("12", "Нормативно-правовые акты"),
                            ("13", "Иные документы"),
                        ],
                        default="01",
                        max_length=100,
                        verbose_name="Тип",
                    ),
                ),
                ("duration", models.DateField(verbose_name="Срок действия")),
                (
                    "doc",
                    models.FileField(upload_to="uploads/", verbose_name="Документ"),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="document_to_project",
                        to="project_app.projects",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="document_to_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Документы",
                "verbose_name_plural": "Документы",
            },
        ),
    ]
