name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into VPS and pull code
      run: |
        ssh -o StrictHostKeyChecking=no root@185.20.227.12 'cd /home/django/egs_back && git fetch origin main && git reset --hard origin/main'

    - name: Run deploy script
      run: |
        ssh -o StrictHostKeyChecking=no root@185.20.227.12 'cd /home/django/egs_back && chmod +x deploy.sh && sh deploy.sh'